name: Build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: docker pull pactfoundation/pact-cli:latest
      - name: install
        run: npm i
      - name: build
        run: make ci
        env:
          PACT_BROKER_TOKEN: ${{ secrets.TEST_PACTFLOW_IO_PACT_BROKER_TOKEN }}
          REACT_APP_API_BASE_URL: http://localhost:8080
          PACT_BROKER_BASE_URL: https://test.pact.dius.com.au
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_BRANCH: ${{ github.ref }}
